---
title: "Data analytics"
author: "Group 4"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
setwd("/Users/atnguyen/Downloads/4.SSP")
library(readr)
library(minpack.lm)
features <- read_csv("normalized_variables.csv")
distance <- read_csv("distances.csv")
df <- merge(features, distance)
colnames(df)[which(colnames(df) == '...1')] <- 'id'
```

# Models
```{r , warning=FALSE}
library(caret)
library(MLmetrics)
set.seed(42)

# Split the data 80 training - 20 testing
train_ind <- createDataPartition(df$liveability_score, p = .8, 
                                  list = FALSE, 
                                  times = 1)
df_train <- df[train_ind, ]
df_test  <- df[-train_ind, ]

# Linear model with all variables
lm_all <- lm(liveability_score ~ . -id - postal_code, data = df_train)
summary(lm_all)

# Make prediction for liveability_score on testing data
lm_all_pred <- predict(lm_all, newdata = df_test)
rmse_all <- sqrt(mean((lm_all_pred - df_test$liveability_score)^2))
print(paste("RMSE:", rmse_all))
```

```{r}

# Linear model with `distance`
lm_distance <-  lm(liveability_score ~ prop_university + worker + prop_women + pop_density + Aid + Income + single_family_housing + `Distance GP` + `Distance Hospital` + `Distance Supermarket` + `Distance Department Store` + `Distance Restaurant` + `Distance Day Care` + `Distance School`, data = df_train)
summary(lm_distance)

# Make prediction for liveability_score on testing data
lm_distance_pred <- predict(lm_distance, newdata = df_test)

# RMSE
rmse_distance <- sqrt(mean((lm_distance_pred - df_test$liveability_score)^2))
print(paste("RMSE:", rmse_distance))
```

```{r}
# Linear model with `Whithin 5 km`
lm_within_5 <- lm(liveability_score ~ prop_university + worker + prop_women + pop_density + Aid + Income + single_family_housing + `Within 5 km GP` + `Within 5 km Hospital` + `Within 5 km Supermarket` + `Within 5 km Department Store` + `Within 5 km Restaurant` + `Within 5 km Day Care` + `Within 5 km School`, data = df_train)
summary(lm_within_5)

# Make prediction for liveability_score on testing data
lm_within_5_pred <- predict(lm_within_5, newdata = df_test)

# RMSE
rmse_within5 <- sqrt(mean((lm_within_5_pred - df_test$liveability_score)^2))
print(paste("RMSE:", rmse_within5))
```

```{r}

# Linear model with `Within 5` and `Within_3` 
lm_within_3_5 <-  lm(liveability_score ~ prop_university + worker + prop_women + pop_density + Aid + Income + single_family_housing + `Within 5 km GP` + `Within 5 km Hospital` + `Within 5 km Supermarket` + `Within 5 km Department Store` + `Within 5 km Restaurant` + `Within 5 km Day Care` + `Within 5 km School` + `Within 3 km GP` + `Within 3 km Supermarket` + `Within 3 km Restaurant` + `Within 3 km Day Care` + `Within 3 km School`, data = df_train)
summary(lm_within_3_5)

# Make prediction for liveability_score on testing data
lm_within_3_5_pred <- predict(lm_within_3_5, newdata = df_test)

# RMSE
rmse_within35 <- sqrt(mean((lm_within_3_5_pred - df_test$liveability_score)^2))
print(paste("RMSE:", rmse_within35))
```

```{r warning=FALSE}
# Extract adjusted R-squared values from each model
adj_r_squared_lm_all <- summary(lm_all)$adj.r.squared
adj_r_squared_lm_distance <- summary(lm_distance)$adj.r.squared
adj_r_squared_lm_within_5 <- summary(lm_within_5)$adj.r.squared
adj_r_squared_lm_within_3_5 <- summary(lm_within_3_5)$adj.r.squared

# Create a dataframe to store the results
model_comparison <- data.frame(
  Model = c("All Variables", "Distance", "Within 5 km", "Within 5 and 3 km"),
  Adjusted_R_squared = c(adj_r_squared_lm_all, adj_r_squared_lm_distance, adj_r_squared_lm_within_5, adj_r_squared_lm_within_3_5),
  RMSE = c(rmse_all, rmse_distance, rmse_within5, rmse_within35)
)

# Print the table
print(model_comparison)
```

