---
title: "SSP_Clustering"
author: "Team 04"
date: "2024-04-30"
output: html_document
---

```{r libraries}
library(dplyr)
```

```{r Data Import}
df_com <- read.csv("Data/Commercial space.csv")
df_inc <- read.excel("Data/vso-hoofdstuk-2-2021-income.csv")
```

```{r Data Merging}
# Remove first two letters from District code
df_com$DistrictsAndNeighbourhoods <- substr(df_com$DistrictsAndNeighbourhoods, start = 3, 
                                            stop = nchar(df_com$DistrictsAndNeighbourhoods))

# Rename
df_com <- rename(df_com, gwb_code_8 = DistrictsAndNeighbourhoods)
# Merge

df <- inner_join(df_inc, df_com, by = "gwb_code_8")
```

```{r Integer Conversion, warning=FALSE}
# Convert column to integer value 
columns_to_convert <- c("Average.household.size", "Population.density", "percent.of.single.family.housing", "percent.of.multifamily.housing",
                        "percentage.of.occupied", "percentage.of.empty", "n_low_educated", "n_highschool_educated", 
                        "n_highly_educated", "p_employees", "p_self_employed", "avg_income_per_recipient", 
                        "avg_income_per_capital", "p_belong_40p_w_lowest_income", "p_belong_20p_w_highest_income", 
                        "avg_standardized_income_household", "p_household_lowest_40p_income", 
                        "p_household_highest_20p_income", "p_low_income_household", 
                        "p_household_smaller_bare_social_minimum", "p_household_upto_110p_social_minimum", 
                        "p_househould_upto_120p_social_minimum", "median_wealth_private_house", "n_pp_w_assitance", 
                        "n_pp_w_AO", "n_pp_w_WW", "n_pp_w_state_pension", "DistanceToGPPractice_5", "Within1Km_6", 
                        "Within3Km_7", "Within5Km_8", "DistanceToGPPost_9", "DistanceToPharmacy_10", 
                        "DistanceToHospital_11", "Within5Km_12", "Within10Km_13", "Within20Km_14", 
                        "DistanceToHospital_15", "Within5Km_16", "Within10Km_17", "Within20Km_18", 
                        "DistanceToLargeSupermarket_24", "Within1Km_25", "Within3Km_26", "Within5Km_27", 
                        "DistanceToShopForOtherDailyFood_28", "Within1Km_29", "Within3Km_30", "Within5Km_31", 
                        "DistanceToDepartmentStore_32", "Within5Km_33", "Within10Km_34", "Within20Km_35", 
                        "DistanceToCafeEtc_36", "Within1Km_37", "Within3Km_38", "Within5Km_39", 
                        "DistanceToCafeteriaEtc_40", "Within1Km_41", "Within3Km_42", "Within5Km_43", 
                        "DistanceToRestaurant_44", "Within1Km_45", "Within3Km_46", "Within5Km_47", 
                        "DistanceToHotelEtc_48", "Within5Km_49", "Within105km_50", "Within20Km_51", 
                        "DistanceToDaycareCentres_52", "Within1Km_53", "Within3Km_54", "Within5Km_55", 
                        "DistanceToOutOfSchoolCare_56")

# Convert columns to integer
df[columns_to_convert] <- lapply(df[columns_to_convert], function(x) as.numeric(gsub(",", ".", x)))
```

```{r Row and Column Selection}
# Get rid of rows representing gemeente
df$gwb_code_10 <- substr(df$gwb_code_10, start = 3, stop = nchar(df$gwb_code_10))

df <- df[nchar(df$gwb_code_10) == 8, ]

# Get rid of columns that do not have any values 
columns_to_drop <- c("DistanceToYouthHealthCentre_19", "DistanceToPhysiotherapist_20", 
                     "Within1Km_21", "Within3Km_22", "Within5Km_23", "DistanceToPublicGreenTotal_76",
                     "DistanceToPark_77", "DistanceToRecreationalTerrain_78", "DistanceToForest_79",
                     "DistanceToOpenNatTerrainTotal_80", "DistanceToSemiPublicGreenTotal_83",
                     "DistanceToOpenDryNaturalTerrain_81", "DistanceToOpenWetNaturalTerrain_82", 
                     "DistanceToSportsArea_84", "DistanceToAllotmentGarden_85", "DistanceToRecreationalArea_86", 
                     "DistanceToCemetery_87", "DistanceToRecreationalInlandWaters_88", "RegionType_2")

# Remove columns from df
df <- df[ , !(names(df) %in% columns_to_drop)]

# Remove NA values 
df <- na.omit(df)

# Get rid of repeating columns 
columns_to_drop <- c("gwb_code", "ID", "Encoding_3", "gwb_code_8", "MunicipalityName_1")

df <- df[ , !(names(df) %in% columns_to_drop)]
```

```{r Columns to Factor}
# Convert certain columns to factor 
df$gm_naam <- as.factor(df$gm_naam)
df$ChangeInDistrictOrNeighbourhood_4<-as.factor(df$ChangeInDistrictOrNeighbourhood_4)
```

```{r File Writing}
write.csv(df, file = "C:/Users/VY/Documents/data_preprocessed.csv")
```